=== PeFerreira98/ISEP.Master.TAP_2019_PRJ/resources/aircraft/agenda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="agenda" type="agendaType"/>
  <xs:complexType name="agendaType">
    <xs:sequence>
      <xs:element type="aircraftsType" name="aircrafts" maxOccurs="1" minOccurs="1"/>
      <xs:element type="runwaysType" name="runways" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:positiveInteger" name="maximumDelayTime" use="required"/>
  </xs:complexType>
  <xs:complexType name="aircraftsType">
    <xs:sequence>
      <xs:element type="aircraftType" name="aircraft" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="runwaysType">
    <xs:sequence>
      <xs:element type="runwayType" name="runway" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="aircraftType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:positiveInteger" name="number" use="required"/>
        <xs:attribute type="xs:nonNegativeInteger" name="target" use="required"/>
        <xs:attribute type="classSType" name="class" use="required"/>
        <xs:attribute type="xs:positiveInteger" name="emergency" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="runwayType">
    <xs:sequence>
      <xs:element type="classType" name="class" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:positiveInteger" name="number" use="required"/>
  </xs:complexType>
  <xs:complexType name="classType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="classSType" name="type"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="classSType">
    <xs:restriction base="xs:byte">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="6"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== PeFerreira98/ISEP.Master.TAP_2019_PRJ/resources/aircraft/ms1_test06.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda maximumDelayTime="900" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="agenda.xsd">
    <!-- POS: Longer example  -->
    <aircrafts>
        <aircraft number="1" target="0" class="5"/>
        <aircraft number="2" target="13" class="1"/>
        <aircraft number="3" target="104" class="5"/>
        <aircraft number="4" target="164" class="3"/>
        <aircraft number="5" target="169" class="3"/>
        <aircraft number="6" target="176" class="2"/>
        <aircraft number="7" target="194" class="2"/>
        <aircraft number="8" target="245" class="6"/>
        <aircraft number="9" target="288" class="5"/>
        <aircraft number="10" target="310" class="4"/>
        <aircraft number="11" target="338" class="3"/>
        <aircraft number="12" target="369" class="2"/>
        <aircraft number="13" target="403" class="6"/>
        <aircraft number="14" target="429" class="4"/>
        <aircraft number="15" target="449" class="3"/>
        <aircraft number="16" target="496" class="1"/>
        <aircraft number="17" target="520" class="3"/>
        <aircraft number="18" target="644" class="5"/>
        <aircraft number="19" target="699" class="6"/>
        <aircraft number="20" target="715" class="2"/>
        <aircraft number="21" target="819" class="6"/>
        <aircraft number="22" target="833" class="5"/>
        <aircraft number="23" target="841" class="5"/>
        <aircraft number="24" target="852" class="3"/>
        <aircraft number="25" target="892" class="1"/>
        <aircraft number="26" target="972" class="2"/>
        <aircraft number="27" target="1044" class="4"/>
        <aircraft number="28" target="1054" class="2"/>
        <aircraft number="29" target="1091" class="6"/>
        <aircraft number="30" target="1157" class="6"/>
    </aircrafts>
    <runways>
        <runway number="1">
            <class type="1"/>
            <class type="2"/>
            <class type="3"/>
            <class type="4"/>
            <class type="5"/>
            <class type="6"/>
        </runway>
        <runway number="2">
            <class type="1"/>
            <class type="2"/>
            <class type="4"/>
            <class type="5"/>
        </runway>
    </runways>
</agenda>
